#!/usr/bin/env python

import torch
from pathlib import Path
import argparse
import numpy as np
import pandas as pd
from metrics import *

def generate_stats(pred_path, truth_path, out_path):
    """
    Conducts 1-vs-all assessment of class predictions and saves metrics in 1 CSV per image sample, where each row contains stats for the class corresponding to the row index. 

    Input:
        pred_path: str - Path to directory containing predicted class per pixel for each image as CSV files. Assumes predictions are all from the same model, thus 1 CSV per image.
        truth_path: str - Path to directory containing the truth class per pixel for each image as CSV files. 
        out_path: str - Path to the directory where the generated statistics (as CSV files) will be saved. One CSV per image. Assumes directory is model-specific. 
    
    Output:
        None - File saved to out_path
    """
    for file in pred_path.iterdir():
        num_classes = int((file.name).split("_")[0])
        truth_data = pd.read_csv(truth_path/file.name)

        try:
            pred_data = pd.read_csv(file)
        except Exception:
            raise ValueError(f"{file} cannot be read as a CSV.")
        
        t_preds = torch.from_numpy(pred_data.values)
        t_truth = torch.from_numpy(truth_data.values)

        # Initialize the output directory
        out_path.mkdir(parents=True, exist_ok=True)

        # Initialize list to hold the rows of the result df
        rows = []

        for label in range(num_classes):
            pred_dist = get_pred_distribution(preds_label, num_classes)
            tp, tn, fp, fn = calc_conf_mtx(t_truth, t_preds, label)
            precision, recall, f1_score, accuracy = calc_metrics(tp, tn, fp, fn)

            stats_dict = {
                "tp": tp,
                "tn": tn,
                "fp": fp,
                "fn": fn,
                "precision": precision,
                "recall": recall,
                "f1_score": f1_score,
                "accuracy": accuracy
            }

            stats_dict.update(pred_dist)
            rows.append(stats_dict)

        result = pd.DataFrame(rows)
        result.to_csv(out_path/f"{file.stem}_metrics.csv")


if __name__ == "__main__":
    # Set up argument parser
    parser = argparse.ArgumentParser(description="Process class predictions generated by segmentation models and produce stats/metrics to assess performance.")
    parser.add_argument("--pred_directory", "-pred", type=str, help='Path to the directory containing predictions (1 CSV per image) from a model of interest', required=True)
    parser.add_argument("--truth_directory", "-truth", type=str, help="Path to the directory containing CSVs for each image with the truth label per pixel", required=True)
    parser.add_argument("--out_directory", "-out", type=str, help="Path to directory where ouput metrics will be saved", required=True)

    # Parse arguments
    args = parser.parse_args()

    pred_path = Path(args.pred_directory)
    truth_path = Path(args.truth_directory)
    out_path = Path(args.out_directory)

    # Run the assessment
    
    print(f"Processing predictions from {pred_path}...")
    generate_stats(pred_path, truth_path, out_path)
    print(f"Completed assessing {pred_path} and saved results to {out_path}!")